BGDIINF_SB-1304: Fixed issue when running on k8s
When running the service on k8s we had the following error at startup:

Error: '' is not a valid port number.

This was a conflict between ENV and ARGS in dockerfile.